import streamlit as st
import pandas as pd
import pymysql


@st.cache_resource
def get_connection():
    return pymysql.connect(host='localhost', port=3306, user='root', password='123456', database='financial_dw', charset='utf8mb4')


@st.cache_data(ttl=60)
def load_data(query):
    conn = get_connection()
    df = pd.read_sql(query, conn)
    return df


COLUMN_MAP = {
    'stat_date': '统计日期',
    'customer_id': '客户ID',
    'account_id': '账户ID',
    'holding_market_value': '持仓市值',
    'purchase_amount': '申购金额',
    'redemption_amount': '赎回金额',
    'profit_loss': '盈亏',
    'net_asset_change': '资产净变动',
    'city': '城市',
    'customer_name': '客户姓名',
    'total_aum': '总资产(AUM)',
    'level_name': '客户等级',
    'customer_count': '客户数',
    'ranking': '排名',
    'product_name': '产品名称',
    'product_type': '产品类型',
    'branch': '网点',
    'sales_ranking': '销售排名',
    'sales_share': '销售占比',
    'total_sales_amount': '销售总额',
    'total_redemption_amount': '赎回总额',
    'net_sales_amount': '净销售额',
    'transaction_count': '交易笔数',
    'avg_daily_sales': '日均销售额',
    'weekly_sales_amount': '周销售额',
    'monthly_sales_amount': '月销售额',
    'expected_return': '预期收益率',
    'risk_level': '风险等级',
    'product_risk_level': '产品风险等级',
    'customer_risk_level': '客户风险等级',
    'risk_match_flag': '风险匹配标志',
    'risk_gap': '风险差距',
    'compliance_status': '合规状态',
    'alert_level': '预警级别',
    'alert_type': '预警类型',
    'alert_message': '预警信息',
    'metric_name': '指标名称',
    'metric_value': '指标值',
    'metric_type': '指标类型',
    'total_holding_count': '总持仓数',
    'mismatch_holding_count': '错配持仓数',
    'mismatch_ratio': '错配比例',
    'assessment_status': '测评状态',
    'is_assessment_expired': '是否过期',
    'report_type': '报告类型',
    'customer_growth_rate': '客户增长率',
    'aum_growth_rate': 'AUM增长率',
    'avg_daily_aum': '日均AUM',
    'total_transaction_amount': '总交易额',
    'net_purchase_amount': '净申购金额',
    'transaction_growth_rate': '交易额增长率',
    'total_products': '产品总数',
    'active_products': '在售产品数',
    'product_coverage_rate': '产品覆盖率',
    'transaction_conversion_rate': '交易转化率',
    'new_customers': '新增客户数',
    'churn_customers': '流失客户数',
    'net_customer_growth': '客户净增数',
    'yoy_aum_growth': 'AUM同比增长率',
    'yoy_transaction_growth': '交易额同比增长率',
    'mom_aum_growth': 'AUM环比增长率',
    'mom_transaction_growth': '交易额环比增长率',
    'target_achievement_rate': '目标达成率',
    'dimension_type': '维度类型',
    'dimension_value': '维度值',
    'aum': 'AUM',
    'transaction_amount': '交易额',
    'avg_aum_per_customer': '户均AUM',
    'avg_transaction_per_customer': '户均交易额',
    'anomaly_type': '异常类型',
    'anomaly_level': '异常级别',
    'description': '异常描述',
    'current_value': '当前值',
    'expected_value': '预期值',
    'deviation_rate': '偏差率',
    'affected_customers': '受影响客户数',
    'affected_amount': '受影响金额',
    'net_amount': '净交易金额',
    'total_fee': '总手续费',
    'unique_product_count': '交易产品数',
    'product_types': '交易产品类型',
    'last_transaction_date': '最后交易日期',
    'days_since_last_transaction': '距最后交易天数',
    'total_purchase_amount': '总申购金额',
    'avg_transaction_amount': '平均交易金额',
    'max_transaction_amount': '最大单笔交易金额',
    'transaction_frequency': '交易频率',
    'preferred_product_type': '偏好产品类型',
    'preferred_transaction_hour': '偏好交易时段',
    'large_transaction_count': '大额交易笔数',
    'large_transaction_amount': '大额交易总额',
    'days_inactive': '未交易天数',
    'churn_risk_level': '流失风险等级',
    'churn_risk_score': '流失风险评分',
    'asset_trend': '资产趋势',
    'warning_id': '预警ID',
    'warning_reason': '预警原因',
    'total_customers': '总客户数',
    'active_customers': '活跃客户数'
}

RISK_METRIC_MAP = {
    'risk_mismatch_customer_count': '风险错配客户数',
    'assessment_expired_rate': '测评过期率',
    'high_risk_product_holding_rate': '高风险产品持有率',
    'risk_mismatch_holding_count': '风险错配持仓数',
    'risk_mismatch_holding_market_value': '风险错配持仓市值',
    'compliance_customer_rate': '合规客户占比',
    'warning_customer_count': '预警客户数',
    'violation_customer_count': '违规客户数',
    'avg_risk_gap': '平均风险差距',
    'high_alert_count': '高风险预警数'
}
